# Generated by Django 4.2.7 on 2023-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_total', models.DecimalField(decimal_places=3, max_digits=25)),
                ('sale_qty', models.IntegerField()),
                ('sale_item_name', models.CharField(max_length=25)),
                ('emp_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_total', models.DecimalField(decimal_places=3, max_digits=25)),
                ('spent_qty', models.IntegerField()),
                ('spent_item_name', models.CharField(max_length=25)),
                ('catagory', models.CharField(max_length=25)),
            ],
        ),
    ]
