# Generated by Django 4.2.7 on 2023-11-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spent',
            old_name='catagory',
            new_name='category',
        ),
    ]
